### ISSUE TITLE
Recommendations from Henophidias

### ISSUE THREAD

**Issue by lmaldonadoch** [JasemDuncan/NewsWeek#2]
## Recommendations
> Navbar for large screens is missing
> Space on the sides of the screen seems to be coming from the bootstrap grid gutter. Check out the No Gutter section on the [documentation](https://getbootstrap.com/docs/4.0/layout/grid/)
> There are som labels missing on some of the images
![image](https://user-images.githubusercontent.com/59229758/81305918-80b8ec00-9044-11ea-8a5f-1a219a6f3a33.png)
> Avoid using the same instruction for several sizes i.e. class = "col-12 col-sm-12 col-md-12"
> There is a wrapper missing for larger screens so you won't be able to apply a max-width. Consider adding one.
> Check out the padding and margin of cards so you can remove them as well.
> The column sizes are not exactly as on the original. What Gabriel did was make a container with 2 columns, one column for the first 2 columns of the website and the other one for the right-most part. Then, he divided the first column into 2 other columns to make the leftmost and the middle column. Maybe you can try that out!

This was an awesome job, man! Way to go! It is great how you applied the classes correctly to organize your whole website. Keep it up!

**Comment by JasemDuncan** [comment]
Thank you, done.
