### ISSUE TITLE
Recommendations from Henophidias

### ISSUE THREAD

**Issue by brugobi** [JasemDuncan/NewsWeek#3]
# Recomendations

- using semantic html (articles and sections tags); 
- add footer tag;
- add some links styles; 
- use bootstrap on the footer;
- some sections are missing for a mobile version;
 
## lg version
 - height on in the magazine section
- section below sign up on main content should not be there
 - below editors pick there is a missing section

## md version

 - check the subscribe and newsletter sections near the footer, the positioning is not correct
there is a section missing
- some content over in the magazine that should not be there
the weather and location elements are missing on the navbar

## sm version
 
 - color of the login button on navbar
 - weather and location banners missing
 - spacing after top stories on sm
 - missing more stories section after opinion, it is further down
 - titles missing
 - section missing after the editors pick

# Congrats Jasem, You have been doing a great job so far.

**Comment by JasemDuncan** [comment]
Thank you, done.
